FROM python:3.11-slim

# Build command
# docker build -f ./dockerfile-dev -t history .

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEV 1

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt .

CMD pip install --cache-dir=/root/pip-cache -r requirements.txt && \
  python src/main.py

