version: '3'

services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: dockerfile
    container_name: video-streaming
    ports:
      - 8000:80
    environment:
      - PORT=80
    restart: "no"