version: '3'

services:
  db:
    extends:
      file: docker-compose.infra.yml
      service: db

  mongo-express:
    extends:
      file: docker-compose.infra.yml
      service: mongo-express

  rabbitmq:
     extends:
      file: docker-compose.infra.yml
      service: rabbitmq 

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: dockerfile-dev
    container_name: video-storage
    volumes:
      - ./tmp/azure-storage/pip-cache:/root/pip-cache
      - ./azure-storage/src:/app/src:z       
    ports:
      - "8001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - DEV=1
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: dockerfile-dev
    container_name: video-streaming
    volumes:
      - ./tmp/video-streaming/pip-cache:/root/pip-cache
      - ./video-streaming/src:/app/src:z    
    ports:
      - 8000:80
    environment:
      - PORT=80
      - DBHOST=db:27017
      - DBNAME=video-streaming
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=pass
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672             
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - HISTORY_HOST=history
      - HISTORY_PORT=80
      - DEV=1
    restart: on-failure
    depends_on:
      - rabbitmq
      - db

  history:
    image: history
    build:
      context: ./history
      dockerfile: dockerfile-dev
    container_name: history
    volumes:
      - ./tmp/history/pip-cache:/root/pip-cache
      - ./history/src:/app/src:z
    ports:
      - 8002:80
    environment:
      - PORT=80
      - DBHOST=db:27017
      - DBNAME=video-streaming
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}    
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=pass
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672        
      - DEV=1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - rabbitmq
      - db    


volumes:
  mongodb_data:
  rabbitmq_data:
  rabbitmq_logs: