version: '3'

services:
  db:
    extends:
      file: docker-compose.infra.yml
      service: db

  mongo-express:
    extends:
      file: docker-compose.infra.yml
      service: mongo-express

  rabbitmq:
     extends:
      file: docker-compose.infra.yml
      service: rabbitmq 

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: dockerfile-prod
    container_name: video-storage 
    ports:
      - "8001:80"
    env_file:
      - .env      
    environment:  
      - DEV=0
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: dockerfile-prod
    container_name: video-streaming
    ports:
      - 8000:80
    env_file:
      - .env      
    environment:  
      - DEV=0
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started

  history:
    image: history
    build:
      context: ./history
      dockerfile: dockerfile-prod
    container_name: history
    ports:
      - 8002:80
    env_file:
      - .env      
    environment:  
      - DEV=0
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started

volumes:
  mongodb_data:
  rabbitmq_data:
  rabbitmq_logs: