name: Build Template

on:
  workflow_call:
    inputs:
      DIRECTORY:
        description: 'Service directory'
        required: true   
        type: string

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        cd "${{ inputs.DIRECTORY }}"
        pip install -r requirements.txt
        pytest      