name: Build

on: 
  push:
    branches:
      - '*'
  workflow_dispatch:
      
jobs:
  video-streaming:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: video-streaming 
  metadata:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: metadata 
     

