name: Build

on: 
  push:
    branches:
      - '*'
  workflow_dispatch:
      
jobs:
  video-streaming:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: video-streaming 
  metadata:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: metadata 
  history:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: history    
  azure-storage:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: azure-storage
  gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - name: gateway build and test
        run: |    
          cd gateway
          npm install
  integration-tests:
    runs-on: ubuntu-latest
    env:
      STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp tests/integration/test.env ./.env
          echo -e "\nSTORAGE_ACCESS_KEY=${{ secrets.STORAGE_ACCESS_KEY }}" >> .env
          cat .env
          docker-compose -f docker-compose-prod.yml up --build -d
          sleep 10
      - name: Run the tests   
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 120
          command: |
            env
            cd tests/integration
            pip install -r requirements.txt
            pytest -s           
