name: CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        cd video-streaming
        pip install -r requirements.txt
        pytest