# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to the main branch.
# For real use you might want to restrict this to the "prod" branch.
#

name: Deploy

on:
  # Deploys the microservice on push to the specified subdirectory in the main branch of this code repository.
  push: 
    branches:
      - main
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed      
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch: 

jobs:
  integration-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      STORAGE_ACCESS_KEY: ${{ secrets.STORAGE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp tests/integration/test.env ./.env
          echo -e "\nSTORAGE_ACCESS_KEY=${{ secrets.STORAGE_ACCESS_KEY }}" >> .env
          cat .env
          docker-compose -f docker-compose-prod.yml up --build -d
          sleep 10
      - name: Run the tests   
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 120
          command: |
            env
            cd tests/integration
            pip install -r requirements.txt
            pytest -s 

  deploy-video-streaming:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: video-streaming
      DIRECTORY: video-streaming
      SERVICE_TYPE: ClusterIP

  deploy-metadata:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: metadata
      DIRECTORY: metadata  
      SERVICE_TYPE: ClusterIP

  deploy-history:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: history
      DIRECTORY: history
      SERVICE_TYPE: ClusterIP

  deploy-azure-storage:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: azure-storage
      DIRECTORY: azure-storage
      SERVICE_TYPE: ClusterIP

  deploy-gateway:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: gateway
      DIRECTORY: gateway
      SERVICE_TYPE: LoadBalancer