name: Deploy

on:
  workflow_call:
    inputs:
      NAME:
        description: 'Service name'
        required: true
        type: string
      DIRECTORY:
        description: 'Service directory'
        required: true   
        type: string
    secrets:
      CONTAINER_REGISTRY: 
        description: "Container registry host"
        required: true
      REGISTRY_UN: 
        description: "Container registry username"
        required: true
      REGISTRY_PW: 
        description: "Container registry username"
        required: true        

env:
  VERSION: ${{ github.run_id }}

jobs:
  deploy-service:
    runs-on: ubuntu-latest 
    env:
      NAME: "${{ inputs.NAME }}"
      DIRECTORY: "${{ inputs.DIRECTORY }}"    
    steps:
      # Build and publish the image
      - uses: actions/checkout@v3
      - run: ./scripts/cd/image-build.sh
      
      - name: Publish
        run: ./scripts/cd/image-push.sh

      # Installs Kubectl and connects it to the cluster.
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.29.4
      
      # Expands the configuration template and deploys the microservice.
      - name: Deploy
        run: ./scripts/cd/deploy.sh