# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to the main branch.
# For real use you might want to restrict this to the "prod" branch.
#

name: Deploy

on:
  # Deploys the microservice on push to the specified subdirectory in the main branch of this code repository.
  push: 
    branches:
      - main
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed      
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch: 

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -f docker-compose-prod.yml up --build
      - name: Run the tests
        run: |
          cd tests/integration
          pip install -r requirements.txt
          pytest -s

  deploy-video-streaming:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: video-streaming
      DIRECTORY: video-streaming    
