# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to the main branch.
# For real use you might want to restrict this to the "prod" branch.
#

name: Deploy

on:
  # Deploys the microservice on push to the specified subdirectory in the main branch of this code repository.
  push: 
    branches:
      - main
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: 
      - completed      
  # Allows deployment to be invoked manually through the GitHub Actions user interface.
  workflow_dispatch: 

jobs:
  deploy-video-streaming:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: video-streaming
      DIRECTORY: video-streaming

  deploy-metadata:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: metadata
      DIRECTORY: metadata    
  deploy-history:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: history
      DIRECTORY: history    
  deploy-azure-storage:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: azure-storage
      DIRECTORY: azure-storage    
  deploy-gateway:
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: gateway
      DIRECTORY: gateway
      SERVICE_TYPE: LoadBalancer