name: Gateway

on: 
  push:
    branches:
      - '*'
    paths:
      - gateway/**       
  workflow_dispatch:

jobs:      
  build-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - name: gateway build and test
        run: |    
          cd gateway
          npm install
  deploy-gateway:
    if: github.ref == 'refs/heads/main'
    needs: build-gateway
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: gateway
      DIRECTORY: gateway
      SERVICE_TYPE: ClusterIP          