name: Gateway

on: 
  push:
    branches:
      - '*'
    paths:
      - gateway/**       
  workflow_dispatch:

jobs:      
  gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
      - name: gateway build and test
        run: |    
          cd gateway
          npm install