name: Hello world

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run the shell script
        run: ./index.sh