name: History

on: 
  push:
    branches:
      - '*'
    paths:
      - history/**
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  build-history:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: history
  deploy-history:
    if: github.ref == 'refs/heads/main'
    needs: build-history
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: history
      DIRECTORY: history
      SERVICE_TYPE: ClusterIP       