name: Metadata

on: 
  push:
    branches:
      - '*'
    paths:
      - metadata/**
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  metadata:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: metadata 