name: Metadata

on: 
  push:
    branches:
      - '*'
    paths:
      - metadata/**
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  build-metadata:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: metadata
  deploy-metadata:
    if: github.ref == 'refs/heads/main'
    needs: build-metadata
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: metadata
      DIRECTORY: metadata
      SERVICE_TYPE: ClusterIP        