name: Storage

on: 
  push:
    branches:
      - '*'
    paths:
      - azure-storage/**
      - .github/workflows/storage-service.yaml   
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  build-azure-storage:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: azure-storage 
  deploy-azure-storage:
    if: github.ref == 'refs/heads/main'
    needs: build-azure-storage
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: azure-storage
      DIRECTORY: azure-storage
      SERVICE_TYPE: ClusterIP         