name: Video Streaming

on: 
  push:
    branches:
      - '*'
    paths:
      - video-streaming/**
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  build-video-streaming:
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: video-streaming 
  deploy-video-streaming:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-template.yaml
    secrets: inherit
    with:
      NAME: video-streaming
      DIRECTORY: video-streaming
      SERVICE_TYPE: ClusterIP      