name: Video Streaming

on: 
  push:
    branches:
      - '*'
    paths:
      - video-streaming/**
  workflow_run:
    workflows: ["Common"]
    branches: [main]
    types: 
      - completed         
  workflow_dispatch:

jobs:      
  video-streaming:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build-template.yaml
    with:
      DIRECTORY: video-streaming 